### ISSUE TITLE
Can't use in AWS Lambda

### ISSUE THREAD

**Issue by Gustavo-Contreiras-Hotels-at-Home** [aadityachakravarty/magento-api-rest#9]
Already tried to import magento-api-rest in all known ways.
No matter what I do I keep receiving the response below.
```
Response
{
  "errorType": "ReferenceError",
  "errorMessage": "Magento is not defined",
  "trace": [
    "ReferenceError: Magento is not defined",
    "    at Runtime.handler (file:///var/task/index.mjs:6:20)",
    "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1089:29)"
  ]
}
```

**Comment by Gustavo-Contreiras-Hotels-at-Home** [comment]
This way it worked:
```
import MagentoRestApi from "magento-api-rest";

export const handler = async(event) => {
    
    const client = new MagentoRestApi.default({
        'url': process.env.MAGENTO_URL,
        'consumerKey': process.env.MAGENTO_CONSUMER_KEY,
        'consumerSecret': process.env.MAGENTO_CONSUMER_SECRET,
        'accessToken': process.env.MAGENTO_ACCESS_TOKEN,
        'tokenSecret': process.env.MAGENTO_TOKEN_SECRET,
    });
    
    let params = {
        $from: event.from || "2022-11-01 01:22:47",
        $to: event.to || "2023-02-01 11:22:47",
        $sort: {
            "created_at": "desc"
        },
        $perPage: event.perPage || 200,
        $page: event.page || 1
    }
    
    return client.get('orders', params).then((response) => {
        return {
            statusCode: response.status,
            body: response.data,
        }
    })
};
```
